//! P language skeleton export for model checking.
//!
//! The output is a starting point a designer fills in, not a verified
//! translation. Representation:
//!
//! - `type tRegistry = map[string, machine];` and `event eWire: tRegistry;`
//!   wire every instance to every other before anything runs.
//! - Each Cascade event is a P event; a declared payload becomes a named
//!   tuple type `t<Event>` whose fields are typed `any`. Each trigger is an
//!   event `e<Machine>_<trigger>` without payload.
//! - Each Cascade machine is a P machine (see [`machines`]): nested states
//!   are flattened to their atomic and final states named by path
//!   (`running.fetching` → `running_fetching`), transitions declared on a
//!   compound state are copied to its descendants (innermost wins), and
//!   emits are `send`s to every subscribed controller.
//! - Each controller is a P machine that receives its events and sends
//!   triggers (see [`controllers`]).
//! - `TestDriver` creates and wires one instance of everything and lets the
//!   external sources fire triggers nondeterministically for a bounded
//!   number of steps (see [`driver`]); `test tcSystem` runs it.
//!
//! Limits:
//!
//! - One instance per machine: target selectors are comments; fan-out and
//!   spawn are TODOs.
//! - Guards and `when` conditions are free text, so they become
//!   nondeterministic choices (`$`) with the text as a comment.
//! - History states are approximated by their parent's default entry.
//! - States `ignore` the triggers they do not accept, matching Cascade's
//!   "the fire is dropped"; remove those lines to have P report them.
//! - Payload field types are `any` and payload values `default(...)`.
//! - No specifications (monitors) are generated; add them for the
//!   properties to check.

mod controllers;
mod driver;
mod machines;
mod names;
mod writer;

use cascade_core::Model;

use names::{Names, REGISTRY_TYPE, WIRE_EVENT};
use writer::Writer;

/// A P program skeleton for the model.
pub(crate) fn export(model: &Model) -> String {
    let names = Names::allocate(model);
    let mut w = Writer::default();
    write_header(&mut w, model);
    w.blank();
    write_declarations(&mut w, model, &names);
    for mid in model.machine_ids() {
        w.blank();
        machines::write_machine(&mut w, model, &names, mid);
    }
    for cid in model.controller_ids() {
        w.blank();
        controllers::write_controller(&mut w, model, &names, cid);
    }
    w.blank();
    driver::write_driver(&mut w, model, &names);
    w.blank();
    driver::write_test(&mut w, model, &names);
    w.finish()
}

fn write_header(w: &mut Writer, model: &Model) {
    match &model.definition().system {
        Some(system) => w.comment(&format!("P skeleton generated by Cascade for {}.", system.value)),
        None => w.comment("P skeleton generated by Cascade."),
    }
    for line in [
        "",
        "Mapping:",
        "- Every Cascade machine and controller is a P machine; the test driver creates one",
        "  instance of each and sends all of them the registry of instances (eWire).",
        "- Triggers are events e<Machine>_<trigger>; Cascade events keep their names, with a",
        "  named-tuple payload type t<Event> (fields typed `any`) when a payload is declared.",
        "- Nested states are flattened to atomic and final states named by path; transitions",
        "  on a compound state apply to its descendants (innermost wins).",
        "- Emitted events are sent to every subscribed controller; controllers send the",
        "  triggers their rules fire.",
        "",
        "Limits (fill these in):",
        "- One instance per machine: target selectors are comments, fan-out and spawn TODOs.",
        "- Guards and conditions are free text: they are nondeterministic choices ($).",
        "- History states enter their parent's default state.",
        "- States ignore triggers they do not accept, as Cascade drops them; remove the",
        "  ignore lines to have P report dropped triggers.",
        "- No specification monitors are generated.",
    ] {
        if line.is_empty() {
            w.line("//");
        } else {
            w.comment(line);
        }
    }
}

fn write_declarations(w: &mut Writer, model: &Model, names: &Names) {
    w.line(&format!("type {REGISTRY_TYPE} = map[string, machine];"));
    w.line(&format!("event {WIRE_EVENT}: {REGISTRY_TYPE};"));

    if model.event_count() > 0 {
        w.blank();
        w.comment("Cascade events, sent by transitions to the controllers subscribed to them.");
        for (eid, _) in model.events() {
            let event = names.event(eid);
            match names.payload_type(eid) {
                Some(ty) => {
                    let fields: Vec<String> = names.payload_fields(eid).iter().map(|f| format!("{f}: any")).collect();
                    w.line(&format!("type {ty} = ({});", fields.join(", ")));
                    w.line(&format!("event {event}: {ty};"));
                }
                None => w.line(&format!("event {event};")),
            }
        }
    }

    if model.trigger_count() > 0 {
        w.blank();
        w.comment("Triggers, sent to machines by controllers and the test driver.");
        for (tid, _) in model.triggers() {
            w.line(&format!("event {};", names.trigger(tid)));
        }
    }
}
